# KubeJS Konfigürasyonu

# Debug modu - Betik hataları hakkında ayrıntılı log
debug.enable_startup_log=true
debug.dump_chunks=false
debug.dump_classes=false

# Betik kaynağı
script.dir=kubejs

# Maksimum script boyutu (byte)
max_script_size=20971520

# Event'lerin iptal edilmesi
event.allow_cancel=true

# Veri tabanı sıkıştırması
compress.enable_gzip=true

# Dinamik klasörlerin izin verilmesi
dynamic.dir.enabled=true

# Logging düzeyi
logging.level=INFO

# Kütüphane klasörü
lib.dir=kubejs/lib

# Server komutu önek
command.prefix=/kubejs
